-- ============================================================================
-- Kairo · AI Prep Engine — PostgreSQL / Supabase schema
-- ============================================================================
-- Run this whole file once in the Supabase SQL editor. It is idempotent.
--
-- Design notes
--   * Every user-owned row carries user_id and is protected by RLS.
--   * The background build pipeline runs with the service-role key, which
--     bypasses RLS by design. Client reads always go through RLS.
--   * `blueprint_cache` is global (service-role only) so a plan skeleton
--     computed for "GATE ECE / beginner / 6mo" is reused across users
--     instead of being re-generated by the model every time.
-- ============================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin create type prep_type     as enum ('exam','skill','hybrid');
exception when duplicate_object then null; end $$;

do $$ begin create type plan_status   as enum ('draft','building','ready','failed','archived','completed');
exception when duplicate_object then null; end $$;

do $$ begin create type item_kind     as enum ('learn','practice','review','project','assess','mock','buffer');
exception when duplicate_object then null; end $$;

do $$ begin create type item_status   as enum ('pending','done','skipped');
exception when duplicate_object then null; end $$;

do $$ begin create type resource_kind as enum ('video','playlist','article','doc','book','course','practice','paper');
exception when duplicate_object then null; end $$;

do $$ begin create type question_kind as enum ('mcq','short','flash');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- 1. profiles (1:1 with auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url   text,
  timezone     text        not null default 'UTC',
  theme        text        not null default 'dark',
  onboarded    boolean     not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $fn$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',
             new.raw_user_meta_data->>'name',
             split_part(coalesce(new.email,'learner@kairo'), '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end $fn$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 2. plans
-- ---------------------------------------------------------------------------
create table if not exists public.plans (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid        not null references auth.users(id) on delete cascade,

  title           text        not null,
  prep_type       prep_type   not null default 'skill',
  subject_slug    text,
  status          plan_status not null default 'draft',

  start_date      date        not null default current_date,
  target_date     date        not null,
  weekday_minutes int         not null default 120,
  weekend_minutes int         not null default 240,
  rest_days       int[]       not null default '{}',   -- 0=Sun … 6=Sat

  skill_level     text        not null default 'beginner',
  intake          jsonb       not null default '{}'::jsonb,
  blueprint       jsonb       not null default '{}'::jsonb,
  digest          text,

  total_items     int         not null default 0,
  done_items      int         not null default 0,

  build_error     text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint plans_dates_ck check (target_date > start_date)
);
create index if not exists plans_user_idx    on public.plans(user_id, created_at desc);
create index if not exists plans_subject_idx on public.plans(subject_slug);

-- ---------------------------------------------------------------------------
-- 3. plan_events (build telemetry, streamed to the UI)
-- ---------------------------------------------------------------------------
create table if not exists public.plan_events (
  id         bigserial primary key,
  plan_id    uuid        not null references public.plans(id) on delete cascade,
  user_id    uuid        not null references auth.users(id)   on delete cascade,
  stage      text        not null,
  status     text        not null default 'running',
  message    text,
  meta       jsonb       not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists plan_events_plan_idx on public.plan_events(plan_id, id);

-- ---------------------------------------------------------------------------
-- 4. units → topics
-- ---------------------------------------------------------------------------
create table if not exists public.units (
  id         uuid primary key default gen_random_uuid(),
  plan_id    uuid         not null references public.plans(id) on delete cascade,
  user_id    uuid         not null references auth.users(id)   on delete cascade,
  idx        int          not null,
  title      text         not null,
  summary    text,
  weight     numeric(5,2) not null default 1,
  created_at timestamptz  not null default now(),
  unique (plan_id, idx)
);
create index if not exists units_plan_idx on public.units(plan_id, idx);

create table if not exists public.topics (
  id          uuid primary key default gen_random_uuid(),
  plan_id     uuid         not null references public.plans(id) on delete cascade,
  unit_id     uuid         not null references public.units(id) on delete cascade,
  user_id     uuid         not null references auth.users(id)   on delete cascade,
  idx         int          not null,
  title       text         not null,
  summary     text,
  outcomes    text[]       not null default '{}',
  keywords    text[]       not null default '{}',
  est_minutes int          not null default 90,
  difficulty  int          not null default 3,
  weight      numeric(5,2) not null default 1,
  depends_on  int[]        not null default '{}',
  mastery     int          not null default 0,
  created_at  timestamptz  not null default now(),
  unique (plan_id, idx)
);
create index if not exists topics_plan_idx on public.topics(plan_id, idx);
create index if not exists topics_unit_idx on public.topics(unit_id, idx);

-- ---------------------------------------------------------------------------
-- 5. resources (API-verified learning material)
-- ---------------------------------------------------------------------------
create table if not exists public.resources (
  id            uuid primary key default gen_random_uuid(),
  plan_id       uuid          not null references public.plans(id) on delete cascade,
  user_id       uuid          not null references auth.users(id)   on delete cascade,
  kind          resource_kind not null,
  title         text          not null,
  url           text          not null,
  source        text,
  author        text,
  description   text,
  thumbnail_url text,
  duration_sec  int,
  published_at  timestamptz,
  metrics       jsonb         not null default '{}'::jsonb,
  score         numeric(6,3)  not null default 0,
  why           text,
  saved         boolean       not null default false,
  created_at    timestamptz   not null default now(),
  unique (plan_id, url)
);
create index if not exists resources_plan_idx on public.resources(plan_id, score desc);

create table if not exists public.topic_resources (
  topic_id    uuid not null references public.topics(id)    on delete cascade,
  resource_id uuid not null references public.resources(id) on delete cascade,
  plan_id     uuid not null references public.plans(id)     on delete cascade,
  user_id     uuid not null references auth.users(id)       on delete cascade,
  rank        int  not null default 0,
  primary key (topic_id, resource_id)
);
create index if not exists topic_resources_topic_idx on public.topic_resources(topic_id, rank);

-- ---------------------------------------------------------------------------
-- 6. sessions → session_items (the day-by-day prep map)
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  id              uuid primary key default gen_random_uuid(),
  plan_id         uuid        not null references public.plans(id) on delete cascade,
  user_id         uuid        not null references auth.users(id)   on delete cascade,
  day_index       int         not null,
  scheduled_on    date        not null,
  planned_minutes int         not null default 0,
  headline        text,
  created_at      timestamptz not null default now(),
  unique (plan_id, day_index)
);
create index if not exists sessions_plan_date_idx on public.sessions(plan_id, scheduled_on);

create table if not exists public.session_items (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid        not null references public.sessions(id) on delete cascade,
  plan_id      uuid        not null references public.plans(id)    on delete cascade,
  user_id      uuid        not null references auth.users(id)      on delete cascade,
  topic_id     uuid        references public.topics(id)    on delete set null,
  resource_id  uuid        references public.resources(id) on delete set null,
  idx          int         not null default 0,
  kind         item_kind   not null default 'learn',
  title        text        not null,
  detail       text,
  est_minutes  int         not null default 30,
  status       item_status not null default 'pending',
  completed_at timestamptz,
  created_at   timestamptz not null default now()
);
create index if not exists session_items_session_idx on public.session_items(session_id, idx);
create index if not exists session_items_plan_idx    on public.session_items(plan_id, status);
create index if not exists session_items_topic_idx   on public.session_items(topic_id);

-- ---------------------------------------------------------------------------
-- 7. questions + reviews (drill engine, SM-2 spaced repetition)
-- ---------------------------------------------------------------------------
create table if not exists public.questions (
  id          uuid primary key default gen_random_uuid(),
  plan_id     uuid          not null references public.plans(id)  on delete cascade,
  topic_id    uuid          not null references public.topics(id) on delete cascade,
  user_id     uuid          not null references auth.users(id)    on delete cascade,
  kind        question_kind not null default 'mcq',
  stem        text          not null,
  options     jsonb         not null default '[]'::jsonb,
  answer      text          not null,
  explanation text,
  difficulty  int           not null default 3,
  created_at  timestamptz   not null default now()
);
create index if not exists questions_topic_idx on public.questions(topic_id);

create table if not exists public.reviews (
  id            uuid primary key default gen_random_uuid(),
  question_id   uuid         not null references public.questions(id) on delete cascade,
  user_id       uuid         not null references auth.users(id)       on delete cascade,
  plan_id       uuid         not null references public.plans(id)     on delete cascade,
  topic_id      uuid         not null references public.topics(id)    on delete cascade,
  ease          numeric(4,2) not null default 2.5,
  interval_days int          not null default 0,
  repetitions   int          not null default 0,
  lapses        int          not null default 0,
  due_on        date         not null default current_date,
  last_grade    int,
  last_seen_at  timestamptz,
  unique (question_id, user_id)
);
create index if not exists reviews_due_idx on public.reviews(user_id, plan_id, due_on);

-- ---------------------------------------------------------------------------
-- 8. mocks
-- ---------------------------------------------------------------------------
create table if not exists public.mocks (
  id           uuid primary key default gen_random_uuid(),
  plan_id      uuid        not null references public.plans(id) on delete cascade,
  user_id      uuid        not null references auth.users(id)   on delete cascade,
  title        text        not null,
  scheduled_on date,
  duration_min int         not null default 60,
  topic_ids    uuid[]      not null default '{}',
  question_ids uuid[]      not null default '{}',
  score        numeric(5,2),
  taken_at     timestamptz,
  breakdown    jsonb       not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);
create index if not exists mocks_plan_idx on public.mocks(plan_id, scheduled_on);

-- ---------------------------------------------------------------------------
-- 9. study_logs (streaks, time-on-task, pace analytics)
-- ---------------------------------------------------------------------------
create table if not exists public.study_logs (
  id         uuid primary key default gen_random_uuid(),
  plan_id    uuid        not null references public.plans(id) on delete cascade,
  user_id    uuid        not null references auth.users(id)   on delete cascade,
  logged_on  date        not null default current_date,
  minutes    int         not null default 0,
  items_done int         not null default 0,
  source     text        not null default 'session',
  created_at timestamptz not null default now()
);
create index if not exists study_logs_idx on public.study_logs(user_id, plan_id, logged_on desc);

-- ---------------------------------------------------------------------------
-- 10. chats + messages
-- ---------------------------------------------------------------------------
create table if not exists public.chats (
  id         uuid primary key default gen_random_uuid(),
  plan_id    uuid        not null references public.plans(id) on delete cascade unique,
  user_id    uuid        not null references auth.users(id)   on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id         uuid primary key default gen_random_uuid(),
  chat_id    uuid        not null references public.chats(id) on delete cascade,
  user_id    uuid        not null references auth.users(id)   on delete cascade,
  role       text        not null check (role in ('user','assistant','system')),
  content    text        not null,
  tokens     int,
  created_at timestamptz not null default now()
);
create index if not exists messages_chat_idx on public.messages(chat_id, created_at);

-- ---------------------------------------------------------------------------
-- 11. blueprint_cache (cross-user reuse of generated structures)
-- ---------------------------------------------------------------------------
create table if not exists public.blueprint_cache (
  cache_key  text primary key,
  payload    jsonb       not null,
  hits       int         not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Triggers: updated_at + denormalised plan counters
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $fn$
begin new.updated_at = now(); return new; end $fn$;

drop trigger if exists tr_profiles_touch on public.profiles;
create trigger tr_profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists tr_plans_touch on public.plans;
create trigger tr_plans_touch before update on public.plans
  for each row execute function public.touch_updated_at();

create or replace function public.sync_plan_counters()
returns trigger language plpgsql security definer set search_path = public as $fn$
declare pid uuid;
begin
  pid := coalesce(new.plan_id, old.plan_id);
  update public.plans p
     set total_items = sub.total,
         done_items  = sub.done
    from (
      select count(*)::int as total,
             count(*) filter (where status = 'done')::int as done
        from public.session_items where plan_id = pid
    ) sub
   where p.id = pid;
  return coalesce(new, old);
end $fn$;

drop trigger if exists tr_items_counters on public.session_items;
create trigger tr_items_counters
  after insert or update of status or delete on public.session_items
  for each row execute function public.sync_plan_counters();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles        enable row level security;
alter table public.plans           enable row level security;
alter table public.plan_events     enable row level security;
alter table public.units           enable row level security;
alter table public.topics          enable row level security;
alter table public.resources       enable row level security;
alter table public.topic_resources enable row level security;
alter table public.sessions        enable row level security;
alter table public.session_items   enable row level security;
alter table public.questions       enable row level security;
alter table public.reviews         enable row level security;
alter table public.mocks           enable row level security;
alter table public.study_logs      enable row level security;
alter table public.chats           enable row level security;
alter table public.messages        enable row level security;
alter table public.blueprint_cache enable row level security;  -- deny-all: service role only

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

-- Every other user-owned table gets the identical owner policy.
do $$
declare t text;
begin
  foreach t in array array[
    'plans','plan_events','units','topics','resources','topic_resources',
    'sessions','session_items','questions','reviews','mocks','study_logs',
    'chats','messages'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_owner', t);
    execute format(
      'create policy %I on public.%I for all
         using (auth.uid() = user_id) with check (auth.uid() = user_id)',
      t || '_owner', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Realtime (build progress + item ticks stream to the client)
-- ---------------------------------------------------------------------------
do $$ begin alter publication supabase_realtime add table public.plan_events;
exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.plans;
exception when duplicate_object then null; when undefined_object then null; end $$;
